language: php

before_script:
  - sudo apt-get update
  - sudo apt-get install python-software-properties -y
  - sudo add-apt-repository ppa:eyecreate/haxe -y
  - sudo apt-get update
  - sudo apt-get install haxe -y
  - sudo apt-get install gcc-multilib g++-multilib -y
  - mkdir ~/haxelib
  - haxelib setup ~/haxelib
  - haxelib install hxcpp
  - haxelib install munit
  - haxelib git cocktail-url https://github.com/haxecocktail/cocktail-url
  - haxelib git cocktail-css-selector https://github.com/haxecocktail/cocktail-css-selector
  - haxelib git cocktail-dom-event https://github.com/haxecocktail/cocktail-dom-event
  - haxelib git cocktail-dom https://github.com/haxecocktail/cocktail-dom
  - mkdir build
  - mkdir report

script:
  - haxelib run munit test -neko -cpp
